### ISSUE TITLE
Failed to Export Identity

### ISSUE THREAD

**Issue by godrei** [bitrise-tools/codesigndoc#1]
codesigndoc successfully found the required Identities/Certificates and Provisioning Profiles, but the Identities/Certificates export failed.

Error:

```
INFO[19:17:04]  * Exporting Identity: iPhone Developer: XYZ (XYZ)
FATA[19:17:04] Failed to Export Identity: FindIdentity: failed to get 'labl' property: getCFDictValueUTF8String: failed to convert value to string
```

**Comment by viktorbenei** [comment]
Fixed in https://github.com/bitrise-tools/codesigndoc/pull/2
