### ISSUE TITLE
There should be a way to export the Identities.p12 with a password

### ISSUE THREAD

**Issue by emablekos** [bitrise-tools/codesigndoc#14]

**Comment by viktorbenei** [comment]
Thanks for the feature request! ;)

**Comment by viktorbenei** [comment]
implemented in https://github.com/bitrise-tools/codesigndoc/pull/16

**Comment by viktorbenei** [comment]
Just one note, this mode can't be enabled if you run the one-liner install script!

To use this option you'll have to install `codesigndoc`, and manually call it with the `--ask-pass` flag. That said, "installing" `codesigndoc` is as easy as downloading the release binary from, allow it to run (`chmod +x`) and then run it; step by step guide is here: https://github.com/bitrise-tools/codesigndoc#manual-install--run

Once v0.9.11 is released (in the next couple of minutes) you'll be able to run `codesigndoc scan --ask-pass`, which will present the usual password prompt (the same one you get when you export from Keychain Access)

**Comment by viktorbenei** [comment]
v0.9.11 released - https://github.com/bitrise-tools/codesigndoc/releases/tag/0.9.11 - thanks for the feature request @emablekos ! 🚀
