### ISSUE TITLE
Failed to archive Xcode project when documents(xib’s) updated in Xcode8 

### ISSUE THREAD

**Issue by susmithashali** [bitrise-tools/codesigndoc#21]
I am able to archive  the app from Xcode8 and generated valid .ipa. When I tried to archive from codesigndoc tool, archive failed with error : Failed to run Xcode Archive: Failed to Archive, error: Failed to run xcodebuild command, error: exit status 65.

Here is the xcodebuild-output.log error message.

error: The document “(null)” requires Xcode 8.0 or later.
Recovery Suggestion: This version does not support documents saved in the Xcode 8 format. Open this document with Xcode 8.0 or later.
2016-10-04 17:14:18.574 ibtoold[17568:1240135] Exception raised while unarchiving document objects - IBDocumentMissingCapabilityException

Appreciate if you can help me in resolving this issue. Thank you.

**Comment by viktorbenei** [comment]
what's the output if you run `xcodebuild -version` in your Terminal?

**Comment by susmithashali** [comment]
Somehow the command line Xcode version was pointing to 7.3.1.  I updated to Xcode8 version, now I could archive the project. Thank you for pointing towards the right setting. It was a total miss from my end.

**Comment by viktorbenei** [comment]
No problem at all - for future record, if anyone else would have this issue:

if you have more than one Xcode installed, and `xcodebuild -version` doesn't point to the right version, you can specify which Xcode should be active in the Terminal by running:

```
sudo xcode-select --switch /path/to/the/right/Xcode.app
```
