### ISSUE TITLE
error: Failed to parse Provisioning Profile content, error: plist: type mismatch: tried to decode array into value of type string

### ISSUE THREAD

**Issue by diskball** [bitrise-tools/codesigndoc#24]
Using codesigndoc with XCode 8.0 on El Capitan. 

Project written in Swift and Automatic Signing is turned on. On the Export step I get the following error:

Failed to export Provisioning Profiles, error: Error during Provisioning Profile search: Failed to read Provisioning Profile infos from file (path: <DEDACTED>/Library/MobileDevice/Provisioning Profiles/<DEDACTED>.mobileprovision), error: Failed to parse Provisioning Profile content, error: plist: type mismatch: tried to decode array into value of type string

**Comment by viktorbenei** [comment]
You should run `codesigndoc` on your own Mac, not on bitrise.io

**Comment by viktorbenei** [comment]
Do you get the same error when you run `codesigndoc` on your Mac?

**Comment by viktorbenei** [comment]
Closing this ticket because of lack of information - @diskball feel free to answer my previous question and I'll re-open it!
