### ISSUE TITLE
Multiple word scheme is truncated ✂️

### ISSUE THREAD

**Issue by andrassomogyi** [bitrise-tools/codesigndoc#25]
Bitrise codesign wizard generates the following command:
```
bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme=Multiple Word Scheme 2"
```
But the generated `xcodebuild` command will be
```
INFO[12:01:19] 🔦  Running an Xcode Archive, to get all the required code signing settings... 
INFO[12:01:19] $ xcodebuild "-workspace" "/Users/heyitsme/path/The Workspace.xcworkspace" "-scheme" "Multiple" "clean" "archive" 
```
Apparently the scheme name is truncated after the first space.

**Comment by viktorbenei** [comment]
Thanks for reporting, we'll try to fix this ASAP.

The workaround right now is to wrap the scheme name in single quotes, unless the scheme includes a single quote of course, something like: 

```
bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme='Multiple Word Scheme 2'"
```

Or with escaped double quotes:

```
bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme=\"Multiple Word Scheme 2\""
```

**Comment by viktorbenei** [comment]
Closing this ticket as this is not an issue of `codesigndoc`, but the bitrise.io website / how the parameter is passed to `codesigndoc` - we have a separate, internal ticket for the bitrise.io website, to fix this issue.

Thanks for reporting @andrassomogyi !
