### ISSUE TITLE
Why include the "clean" target when "archive" always does a clean on its own?

### ISSUE THREAD

**Issue by Sauraus** [bitrise-tools/codesigndoc#30]
AFAIK xcodebuild "archive" will implicitly perform a "clean" why add it?

xcodebuild "-project" "MY_AWESOME_PROJECT.xcodeproj" "-scheme" "Roblox" "clean" "archive"

**Comment by viktorbenei** [comment]
Because it does not ;)
You have to add "clean" to do a full clean build/archive, and only that will include all the code signing options required for an archive.
