### ISSUE TITLE
[ Run failed but archive works]

### ISSUE THREAD

**Issue by Tailcloud** [bitrise-tools/codesigndoc#36]
_Please include the full (Terminal) output of `codesigndoc` -
in Terminal.app you can save the output into a file with `Command+s`_

_In addition to this, if `codesigndoc` generated an Xcode output log, please attach that too._
![image](https://cloud.githubusercontent.com/assets/8122494/24158114/585bc184-0e96-11e7-8aa5-d86af4aa1077.png)

Hello, I am sure my ARCHIVE works in xcode; however, run codesigndoc failed.

**Comment by viktorbenei** [comment]
What's in the log file highlighted in the log? (xcodebuild-output.log)

**Comment by viktorbenei** [comment]
Closing because of the lack of reply. Feel free to reply @Tailcloud and we'll reopen this issue!
