### ISSUE TITLE
Error when workspace name contains space

### ISSUE THREAD

**Issue by andrassomogyi** [bitrise-tools/codesigndoc#4]
FATA[18:01:38] Failed to scan Schemes: Failed to run 'xcodebuild -list': xcodebuild: error: '/Users/user/Example\ Workspace.xcworkspace' does not exist. | error: exit status 66

Tried removing the space, and it reached the scheme selector dialog.

**Comment by viktorbenei** [comment]
Fixed in v0.9.7 - thanks for reporting!
