### ISSUE TITLE
Better / clearer message about what the exported signing files are for

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-tools/codesigndoc#40]
From a user:

> codesign tool was telling me i need A.mobileprovision
> So i only uploaded that one
> The docs were suggesting to upload all files that the tool exports.
> So I did

Fixed the issue.

We should make this clearer in the codesigndoc logs that you most likely need all the exported files if you want to do distribution builds. The "required" signing files are only for development/base signing in most cases (e.g. when Xcode 8 Auto Code Signing is enabled).

Also we should print some info about additional files, that even if you upload all the exported files you might have to upload additional one(s) if you want to do an export with a completely different team, e.g. when using one Apple Dev Team for development & ad-hoc builds, and another one for AppStore/Enterprise distribution. Codesigndoc could maybe also ask for additional team IDs, so it can auto collect the additional distribution files for distribution signing with another team.

**Comment by godrei** [comment]
Hi @viktorbenei ,
we released a [new version of codesigndoc](https://github.com/bitrise-tools/codesigndoc/releases/tag/2.0.0) please try it out and reopen the issue, if the tool's output is still unclear.
