### ISSUE TITLE
Add an option to pass the -sdk parameter to the xcodebuild

### ISSUE THREAD

**Issue by Felipe-Banno** [bitrise-tools/codesigndoc#41]
I have a project that uses a library that supports both mac and ios devices.
If I call xcodebuild without passing the **-sdk iphoneos** parameter, the archive fails.

Everything works fine when I pass the -sdk parameter.

There is no way I can change the library, so could you please add the option to the codesigndoc tool?

Thanks

**Comment by viktorbenei** [comment]
v1.1.0 was just released (https://github.com/bitrise-tools/codesigndoc/releases/tag/1.1.0) and it now has an option to specify the `-sdk` parameter, example:

```
codesigndoc scan xcode --xcodebuild-sdk iphoneos
```

Thanks for reporting @Felipe-Banno ! :)
