### ISSUE TITLE
Fail when exporting identities and provisioning files

### ISSUE THREAD

**Issue by fpena** [bitrise-tools/codesigndoc#43]
There's an error when running: 

`sudo bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh)"`

[Here's](http://cloud.penya.cl/343b0C2a0H2d) the terminal output and the [Xcode build](http://cloud.penya.cl/1X131O440u3v) output.

**Comment by viktorbenei** [comment]
Error from the xcode build log:

```
No profiles for 'com.lucylovestrucks.yervana-dev' were found:  Xcode couldn't find a provisioning profile matching 'com.lucylovestrucks.yervana-dev'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
```

@fpena please make sure that you can archive that specific project & scheme from Xcode.app as the error comes from the `xcodebuild archive` directly.

**Comment by fpena** [comment]
@viktorbenei I can archive this with success. 

<img width="1286" alt="captura de pantalla 2017-06-03 a la s 09 08 13" src="https://cloud.githubusercontent.com/assets/440097/26755141/42bce0ee-483c-11e7-84d9-3feae91af316.png">

**Comment by viktorbenei** [comment]
What was the xcodebuild command you ran?

**Comment by fpena** [comment]
`xcodebuild "-workspace" "/Users/felipepenariveros/Documents/TTT/yervana-ios/Yervana.xcworkspace" "-scheme" "Yervana-Develop" "clean" "archive"`

ps: I changed the name of the scheme recently, but the former error still happens.

**Comment by viktorbenei** [comment]
@fpena did you try to run `codesigndoc` after the scheme change? Did you get the same error?

Asking because the `xcodebuild` command seems to be the exact same command what `codesigndoc` runs, and there's absolutely no magic there, it just runs the command and records the log.

**Comment by fpena** [comment]
@viktorbenei 

tried this.

`bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) scheme=Yervana-Develop"`

still failing. 

<img width="1618" alt="captura de pantalla 2017-06-06 a la s 08 59 48" src="https://user-images.githubusercontent.com/440097/26838952-86c4ae50-4a96-11e7-870d-7dbf7f4084e3.png">

**Comment by viktorbenei** [comment]
Can you please attach the Terminal and the Xcodebuild output logs?

**Comment by fpena** [comment]
@viktorbenei please check the follow PDF from the instruction:

`xcodebuild "-workspace" "/Users/felipepenariveros/Documents/TTT/yervana-ios/Yervana.xcworkspace" "-scheme" "Yervana-Develop" "clean" "archive"`

http://cloud.penya.cl/0c0H1Q2p322C

**Comment by viktorbenei** [comment]
@fpena sorry, I meant the logs of the failing `codesigndoc` (you said you tried it again after running `xcodebuild` with the exact same parameters)

**Comment by fpena** [comment]
@viktorbenei this is the one

http://cloud.penya.cl/1d462m0v3i27

**Comment by viktorbenei** [comment]
Is the `xcodebuild` command the same? The one printed by `codesigndoc` when you run it, and the one you ran yourself.

There's definitely a difference somewhere, as the one you just attached (from `codesigndoc`) includes an error:

```
MWPhotoBrowserPrivate.h:57:5: error: 'MPMoviePlayerViewController' is deprecated: first deprecated in iOS 9.0
    MPMoviePlayerViewController *_currentVideoPlayerViewController;
    ^
```

Which is definitely a code error in the project.

**Comment by fpena** [comment]
Run `ash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) scheme=Yervana-Develop"` again. 

This is what it comes out. 

<img width="1329" alt="captura de pantalla 2017-06-07 a la s 09 47 52" src="https://user-images.githubusercontent.com/440097/26890456-68469422-4b66-11e7-8228-7f65084ef289.png">

Log: http://cloud.penya.cl/3w3h2c2Z1K0H

**Comment by fpena** [comment]
@viktorbenei no updates around this?

**Comment by viktorbenei** [comment]
@fpena this is now a different issue, that keychain fails to export the cert. Not sure what the issue might be. OSStatus -61 means "security write permission error". Did you Allow Access to export when the popup was presented by macOS?

**Comment by viktorbenei** [comment]
@fpena did you manage to solve the issue?

Closing as the issue doesn't seem to be related to codesigndoc, but feel free to comment and we'll reopen it.
