### ISSUE TITLE
Provisioning profiles should be checked for expiration

### ISSUE THREAD

**Issue by lyricsboy** [bitrise-tools/codesigndoc#44]
I had an older, expired, ad hoc provisioning profile in my `~/Library/MobileDevice/Provisioning Profiles` directory that matched the bundle identifier for my target. I did not have the more recently generated (not expired) profile in that directory when I ran `codesigndoc` the first time.

`codesigndoc` picked up the expired profile and didn't report any issues with it. After putting the non-expired profile in place (via opening with Xcode), `codesigndoc` picked up both the expired and non-expired profile during the export process.

It should be fairly simple to add a check for provisioning profile expiration in a similar fashion to the check for certificate expiration. Would this cause any issues?

**Comment by viktorbenei** [comment]
That's a good point and sure, expiration check would be a great addition. To be honest I guess this slipped through as we always suggest everyone to first make sure they can archive in Xcode and run `codesigndoc` after that, and Xcode usually resolves this issue.

I'll add the `enhancement` tag to this as I believe highlighting the fact that a prov profile is expired in the logs would be awesome, maybe with a yellow or red log highlight. Not exporting the expired profile would also be a good idea of course :)

Added `help wanted` tag too as we probably won't have enough time for this in the near future. We'll definitely check back once we have enough time, but if someone would send a PR we would definitely be glad to review it ;)

**Comment by lyricsboy** [comment]
Hey look, someone sent a PR! Someone wrote his first Go code!

**Comment by viktorbenei** [comment]
Awesome, thanks @lyricsboy ! :D I hope it wasn't that painful ;)

Will review it ASAP

**Comment by viktorbenei** [comment]
Released in [v1.2.0](https://github.com/bitrise-tools/codesigndoc/releases/tag/1.2.0) - thanks again @lyricsboy ! ;)
