### ISSUE TITLE
Supporting Visual Studio for Mac

### ISSUE THREAD

**Issue by ptelling** [bitrise-tools/codesigndoc#48]
Xamarin Studio has been superseded by Visual Studio for Mac, meaning the mdtool path is now incorrect.

The simple fix is to change `/Applications/Xamarin Studio.app/Contents/MacOS/mdtool` to `/Applications/Visual Studio.app/Contents/MacOS/vstool` in xamarin.go. However this will break for anyone still running Xamarin Studio.

**Comment by viktorbenei** [comment]
Thanks for reporting @ptelling !

We'll try to work on this ASAP, but of course we would be happy to review & accept a PR if someone has time for it before we would (most likely it'll take at least 2 weeks, maybe more).

**Comment by viktorbenei** [comment]
PR with the fix: https://github.com/bitrise-tools/codesigndoc/pull/49/files

**Comment by viktorbenei** [comment]
Fix released in [v1.3.0](https://github.com/bitrise-tools/codesigndoc/releases/tag/1.3.0) 🎉 

Thanks for reporting @ptelling ! :)
