### ISSUE TITLE
revision: use `github.com/pkg/errors` for errors; unified `walkProvProfiles`

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-tools/codesigndoc#52]
Use https://github.com/pkg/errors for errors, everywhere (used in `walkProvProfiles` and in a couple of related functions now).

Also unify the prov profile "walk", built on `walkProvProfiles`, searching for both `.mobileprovision` and `.provisionprofile`!

**Comment by godrei** [comment]
Hi @viktorbenei ,
i will close this issue, since the mentioned functions are removed, related functions are implemented in go-xcode packages: https://github.com/bitrise-tools/go-xcode/tree/master/profileutil.

**Comment by viktorbenei** [comment]
👍
