### ISSUE TITLE
Failed to run xamarin build command, error MSB4057

### ISSUE THREAD

**Issue by amulware** [bitrise-tools/codesigndoc#56]
The Xamarin script has trouble building our app.

Archiving and signing from within Visual Studio for Mac works just fine, however.

The error seems to be MSB4057, given that that is basically the entire content of the generated log. However, I'm not sure how to debug this further.

The log is full of that error as follows (paths truncated):

```
"/Toggl.sln" (Toggl_Daneel target) (1) ->
"/Toggl.Ultrawave/Toggl.Ultrawave.csproj" (Toggl_Daneel target) (2) ->
  /Toggl.Ultrawave/Toggl.Ultrawave.csproj : error MSB4057: The target "Toggl_Daneel" does not exist in the project.
```
You can see the app's repo here: https://github.com/toggl/mobileapp

I also attached the full log and output of the script.

[xamarin-build-output.log](https://github.com/bitrise-tools/codesigndoc/files/1509914/xamarin-build-output.log)

[terminal.log](https://github.com/bitrise-tools/codesigndoc/files/1509916/terminal.log)

**Comment by kdobmayer** [comment]
Hi, thanks for reporting the issue, we will look into it as soon as possible.

**Comment by godrei** [comment]
Hi @amulware ,
we released a [new version of codesigndoc](https://github.com/bitrise-tools/codesigndoc/releases/tag/2.0.0), please try it out and reopen the issue, if you still see the issue.

**Comment by amulware** [comment]
I'm still getting the same errors as detailed above I'm afraid. Let me know if there is something different/more specific I can try to make it work or get more information.

**Comment by amulware** [comment]
@godrei I don't think I have the right to reopen issues. The button is missing for me.

**Comment by viktorbenei** [comment]
Reopened, we'll check this ASAP!

**Comment by godrei** [comment]
Hi @amulware ,
we released a new version: [2.0.3](https://github.com/bitrise-tools/codesigndoc/releases/tag/2.0.3) which should fix your issue. Could you please try the new version?

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by amulware** [comment]
I can confirm that the error above does no longer occur. It's getting much further into the build process now and then errors for different reasons. That might well be our fault though. Our build configs are a big finicky right now.

We're currently uploading our provisioning files manually though, so I won't be looking further into that for now.

I'll post again or create a new issue if we run into further troubles down the line. :)

**Comment by viktorbenei** [comment]
Glad to hear, thanks for reporting @amulware ! :)
