### ISSUE TITLE
fails to compile on go version go1.10 darwin/amd64

### ISSUE THREAD

**Issue by gedw99** [bitrise-tools/codesigndoc#60]
go version
go version go1.10beta1 darwin/amd64

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build488541265=/tmp/go-build -gno-record-gcc-switches -fno-common"

go get github.com/bitrise-tools/codesigndoc
# github.com/bitrise-tools/codesigndoc/osxkeychain
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:30: cannot use nil as type _Ctype_CFArrayRef in assignment
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:31: cannot use nil as type _Ctype_CFArrayRef in assignment
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:35: cannot use nil as type _Ctype_CFTypeRef in assignment
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:36: cannot use nil as type _Ctype_CFStringRef in assignment
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:44: cannot use nil as type _Ctype_CFStringRef in assignment
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:45: cannot use nil as type _Ctype_CFStringRef in assignment
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:49: cannot convert &itemRefsToExport[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:114: cannot convert identityRef (type _Ctype_CFTypeRef) to type _Ctype_SecIdentityRef
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:122: cannot convert nil to type _Ctype_CFDataRef
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:179: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFDictionaryCreateMutable
../../../../../../bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:179: too many errors

---

Reproduce:

brew info go
brew install go --devel

**Comment by doomsayer13** [comment]
Thanks for reporting.
We'll fix it ASAP.

**Comment by gedw99** [comment]
Ldflag -s worked for now

**Comment by viktorbenei** [comment]
Thanks for reporting & for the info @gedw99 ! ;)

**Comment by gedw99** [comment]
no probs. they changed a few cgo like things with this beta of golang.

you shoudl def report it to the golang team , as i reported a few other cgo fails and they were keen to help either tell you whats changed or fix it on their side..

**Comment by viktorbenei** [comment]
Thanks again @gedw99 , in the name of the Go community as well ! :)

**Comment by viktorbenei** [comment]
We're circling back to this - @gedw99 where & what did you specify? Can you send a PR? Would be really appreciated! :)

**Comment by gedw99** [comment]
@viktorbenei is this still relevent now that everyone is using go 1.10 proper ?

**Comment by viktorbenei** [comment]
@gedw99 still relevant, it seems the regression slipped through, error with go 1.10:

```
go test github.com/bitrise-tools/codesigndoc github.com/bitrise-tools/codesigndoc/cmd github.com/bitrise-tools/codesigndoc/osxkeychain github.com/bitrise-tools/codesigndoc/version github.com/bitrise-tools/codesigndoc/xamarin github.com/bitrise-tools/codesigndoc/xcode
# github.com/bitrise-tools/codesigndoc/osxkeychain
osxkeychain/osxkeychain.go:30: cannot use nil as type _Ctype_CFArrayRef in assignment
osxkeychain/osxkeychain.go:31: cannot use nil as type _Ctype_CFArrayRef in assignment
osxkeychain/osxkeychain.go:35: cannot use nil as type _Ctype_CFTypeRef in assignment
osxkeychain/osxkeychain.go:36: cannot use nil as type _Ctype_CFStringRef in assignment
osxkeychain/osxkeychain.go:44: cannot use nil as type _Ctype_CFStringRef in assignment
osxkeychain/osxkeychain.go:45: cannot use nil as type _Ctype_CFStringRef in assignment
osxkeychain/osxkeychain.go:49: cannot convert &itemRefsToExport[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
osxkeychain/osxkeychain.go:122: cannot convert nil to type _Ctype_CFDataRef
osxkeychain/osxkeychain.go:187: cannot use queryDict (type _Ctype_CFMutableDictionaryRef) as type _Ctype_CFDictionaryRef in argument to func literal
osxkeychain/osxkeychain.go:247: cannot convert retVal (type _Ctype_CFTypeRef) to type *unsafe.Pointer
osxkeychain/osxkeychain.go:247: too many errors
FAIL	github.com/bitrise-tools/codesigndoc/cmd [build failed]
ok  	github.com/bitrise-tools/codesigndoc/xcode	0.018s
```

**Comment by gedw99** [comment]
Passing "Ldflag -s" is what i used to make it compile as a work around.


They changed how cgo works with go 1.10. Have a look here:
https://golang.org/doc/go1.10#cgo

It looks like a ton of code got impacted by this change.
https://github.com/golang/go/issues/24161
- Also using the _Ctype_CFArrayRef, and no solution there from the golang team.

Sorry i cant be more helpful on this one. If it was me i would submit it and reference the 24161 issue...

**Comment by viktorbenei** [comment]
Got it, thanks for the infos @gedw99 ! :)

**Comment by viktorbenei** [comment]
PR to fix this error: https://github.com/bitrise-tools/codesigndoc/pull/68
