### ISSUE TITLE
No signing identity when app name has apostrophe

### ISSUE THREAD

**Issue by kleemedia** [bitrise-tools/codesigndoc#71]
I get this error message
```failed to analyze the archive, error: no signing identity found``` 
when the app "Product Name" contains an apostrophe (i.e. MyApp's)

**Comment by viktorbenei** [comment]
Can you please open a new terminal, run these commands and attach the whole output here? It'd help a lot! :)

**Comment by godrei** [comment]
Closing as we did not receive a reply - @kleemedia  please let us know if we can help with anything and we'll reopen this issue!
