### ISSUE TITLE
Auto script to get provisioning/cert file executed fail

### ISSUE THREAD

**Issue by tonifirnandes** [bitrise-tools/codesigndoc#75]
Hello team,

We need some help.

Auto script to get provisioning/cert file executed fail, error details here :

![image](https://user-images.githubusercontent.com/3122029/39059468-c62f7686-44e8-11e8-9f62-e067138a1bff.png)

As you can see, left terminal picture shown the script process which return failed, the right terminal picture show if actually in my laptop/local machine has the provisioning files to be used.

Error details : 

Tonis-MacBook-Pro:helpster_partner_ios tonifirnandes$ bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme='HelpsterCompany' --certs-only"
 => Creating a temporary directory for codesigndoc ...
 => Downloading version: 2.1.0
 => Downloading codesigndoc from (https://github.com/bitrise-tools/codesigndoc/releases/download/2.1.0/codesigndoc-Darwin-x86_64) to (/var/folders/81/nwc35mb90kl8q13p498ts7_h0000gn/T/codesigndocXXXXXX.5lKfFMr1/codesigndoc) ...
######################################################################## 100.0%
 => Making it executable ...
 => codesigndoc version: 2.1.0
 => Running codesigndoc scan ...

Xcode (xcodebuild) version: Xcode 7.3.1 (Build version 7D1014)

Please drag-and-drop your Xcode Project (.xcodeproj) or Workspace (.xcworkspace) file, 
the one you usually open in Xcode, then hit Enter.

(Note: if you have a Workspace file you should most likely use that) : /Users/tonifirnandes/Documents/ios/helpster_partner_ios/HelpsterCompany.xcodeproj 

🔦  Running an Xcode Archive, to get all the required code signing settings...
$ xcodebuild "-project" "/Users/tonifirnandes/Documents/ios/helpster_partner_ios/HelpsterCompany.xcodeproj" "-scheme" "HelpsterCompany" "clean" "archive" "-archivePath" "/var/folders/81/nwc35mb90kl8q13p498ts7_h0000gn/T/__codesigndoc__737858264/HelpsterCompany.xcarchive"
......

💡  Saving xcodebuild output into file: /Users/tonifirnandes/Documents/ios/helpster_partner_ios/codesigndoc_exports/xcodebuild-output.log
Please check the logfile (/Users/tonifirnandes/Documents/ios/helpster_partner_ios/codesigndoc_exports/xcodebuild-output.log) to see what caused the error
and make sure that you can Archive this project from Xcode!

Open the project: /Users/tonifirnandes/Documents/ios/helpster_partner_ios/HelpsterCompany.xcodeproj
and Archive, using the Scheme: HelpsterCompany

------------------------------
First of all please make sure that you can Archive your app from Xcode.
codesigndoc only works if you can archive your app from Xcode.
If you can, and you get a valid IPA file if you export from Xcode,
please create an issue on GitHub at: https://github.com/bitrise-tools/codesigndoc/issues
with as many details & logs as you can share!
------------------------------

Error: failed to run xcodebuild command, error: exit status 65
Tonis-MacBook-Pro:helpster_partner_ios tonifirnandes$ bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme='HelpsterCompany' --certs-only"
 => Creating a temporary directory for codesigndoc ...
 => Downloading version: 2.1.0
 => Downloading codesigndoc from (https://github.com/bitrise-tools/codesigndoc/releases/download/2.1.0/codesigndoc-Darwin-x86_64) to (/var/folders/81/nwc35mb90kl8q13p498ts7_h0000gn/T/codesigndocXXXXXX.ydcuDYA4/codesigndoc) ...
######################################################################## 100.0%
 => Making it executable ...
 => codesigndoc version: 2.1.0
 => Running codesigndoc scan ...

Export output dir already exists at path: /Users/tonifirnandes/Documents/ios/helpster_partner_ios/codesigndoc_exports

Xcode (xcodebuild) version: Xcode 7.3.1 (Build version 7D1014)

Please drag-and-drop your Xcode Project (.xcodeproj) or Workspace (.xcworkspace) file, 
the one you usually open in Xcode, then hit Enter.

(Note: if you have a Workspace file you should most likely use that) : /Users/tonifirnandes/Documents/ios/helpster_partner_ios/HelpsterCompany.xcworkspace 

🔦  Running an Xcode Archive, to get all the required code signing settings...
$ xcodebuild "-workspace" "/Users/tonifirnandes/Documents/ios/helpster_partner_ios/HelpsterCompany.xcworkspace" "-scheme" "HelpsterCompany" "clean" "archive" "-archivePath" "/var/folders/81/nwc35mb90kl8q13p498ts7_h0000gn/T/__codesigndoc__676386112/HelpsterCompany.xcarchive"
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

.

.
..........................................................................................................................................................................................................................................................................

💡  Saving xcodebuild output into file: /Users/tonifirnandes/Documents/ios/helpster_partner_ios/codesigndoc_exports/xcodebuild-output.log
Please check the logfile (/Users/tonifirnandes/Documents/ios/helpster_partner_ios/codesigndoc_exports/xcodebuild-output.log) to see what caused the error
and make sure that you can Archive this project from Xcode!

Open the project: /Users/tonifirnandes/Documents/ios/helpster_partner_ios/HelpsterCompany.xcworkspace
and Archive, using the Scheme: HelpsterCompany

------------------------------
First of all please make sure that you can Archive your app from Xcode.
codesigndoc only works if you can archive your app from Xcode.
If you can, and you get a valid IPA file if you export from Xcode,
please create an issue on GitHub at: https://github.com/bitrise-tools/codesigndoc/issues
with as many details & logs as you can share!
------------------------------

Error: failed to run xcodebuild command, error: exit status 65

Xcode error log : 
[xcodebuild-output.log](https://github.com/bitrise-tools/codesigndoc/files/1932645/xcodebuild-output.log)

Thanks.

**Comment by viktorbenei** [comment]
Any time ;)
