### ISSUE TITLE
Bash script does nothing

### ISSUE THREAD

**Issue by AceNorth** [bitrise-tools/codesigndoc#89]
When I run the one-liner bash script for XCode, my terminal instance refreshes but nothing else happens. Typing `codesigndoc` gives me `zsh: command not found: codesigndoc` obviously.

_Please include the full (Terminal) output of `codesigndoc` -
in Terminal.app you can save the output into a file with `Command+s`_

_In addition to this, if `codesigndoc` generated an Xcode output log, please attach that too._

**Comment by tamasbazs** [comment]
Hi @AceNorth,
Thank you for reporting the issue! I forwarded it to our tooling team and they'll get back to you if they find something!

**Comment by godrei** [comment]
Hi @AceNorth ,

which terminal app and which shell do you use?

As a workaround, you can download the binary from: https://github.com/bitrise-tools/codesigndoc/releases (`codesigndoc-Darwin-x86_64
`) add executable permission to it: `chmod +x full/path/to/the/binary` and run: `full/path/to/the/binary scan`

**Comment by AceNorth** [comment]
The manual install does work. I don't use any plugins.

**Comment by godrei** [comment]
Do you have any idea how could i reproduce this issue? I'm using iTerm and zsh as well. But i never saw a similar issue, also none of our users reported it.

**Comment by AceNorth** [comment]
Nope! No idea. I'm not getting any errors or output whatsoever, just a reboot of my terminal. If nobody else is experiencing it, must just be a weird edge case.

**Comment by godrei** [comment]
If you would have any more info about the issue, please open a new one with the details and thanks for reporting!
